services:
  test: &default
    image: usergems:php8.2
    build: 
      context: .
      target: dev
      dockerfile: Dockerfile
    command: php artisan test
    working_dir: /app
    volumes:
      - .:/app
  app:
    <<: *default
    command: []
    depends_on:
      - db
      - nginx
  ci:
    <<: *default
    image: usergems:ci
    build: 
      context: .
      target: ci
    entrypoint: []
    volumes: []

  db: &mysql
    image: mysql:8.4
    restart: always
    volumes:
      - usergems-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: usergems
      MYSQL_USER: impacte
      MYSQL_PASSWORD: impacte
      MYSQL_ROOT_PASSWORD: example
  nginx:
    image: nginx:alpine
    ports:
      - "8989:80"
    volumes:
      - ./:/app
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  usergems-volume:
